socket {
	listen 8112;
	host 127.0.0.1;

	domain d00.local {
		root /var/www;
		index index.html;

		location / {
			allow_methods GET POST DELETE;
			autoindex off;
		}
	}

	domain d01.local {
		root /var/www;
		index index.html;

		location / {
			allow_methods GET POST DELETE;
			autoindex off;
		}
	}

	domain d02.local {
		root /var/www;
		index index.html;

		location / {
			allow_methods GET POST DELETE;
			autoindex off;
		}
	}

	domain d03.local {
		root /var/www;
		index index.html;

		location / {
			allow_methods GET POST DELETE;
			autoindex off;
		}
	}

	domain d04.local {
		root /var/www;
		index index.html;

		location / {
			allow_methods GET POST DELETE;
			autoindex off;
		}
	}

	domain d05.local {
		root /var/www;
		index index.html;

		location / {
			allow_methods GET POST DELETE;
			autoindex off;
		}
	}

	domain d06.local {
		root /var/www;
		index index.html;

		location / {
			allow_methods GET POST DELETE;
			autoindex off;
		}
	}

	domain d07.local {
		root /var/www;
		index index.html;

		location / {
			allow_methods GET POST DELETE;
			autoindex off;
		}
	}

	domain d08.local {
		root /var/www;
		index index.html;

		location / {
			allow_methods GET POST DELETE;
			autoindex off;
		}
	}

	domain d09.local {
		root /var/www;
		index index.html;

		location / {
			allow_methods GET POST DELETE;
			autoindex off;
		}
	}

	domain d10.local {
		root /var/www;
		index index.html;

		location / {
			allow_methods GET POST DELETE;
			autoindex off;
		}
	}

	domain d11.local {
		root /var/www;
		index index.html;

		location / {
			allow_methods GET POST DELETE;
			autoindex off;
		}
	}

	domain d12.local {
		root /var/www;
		index index.html;

		location / {
			allow_methods GET POST DELETE;
			autoindex off;
		}
	}

	domain d13.local {
		root /var/www;
		index index.html;

		location / {
			allow_methods GET POST DELETE;
			autoindex off;
		}
	}

	domain d14.local {
		root /var/www;
		index index.html;

		location / {
			allow_methods GET POST DELETE;
			autoindex off;
		}
	}

	domain d15.local {
		root /var/www;
		index index.html;

		location / {
			allow_methods GET POST DELETE;
			autoindex off;
		}
	}

	domain d16.local {
		root /var/www;
		index index.html;

		location / {
			allow_methods GET POST DELETE;
			autoindex off;
		}
	}

	domain d17.local {
		root /var/www;
		index index.html;

		location / {
			allow_methods GET POST DELETE;
			autoindex off;
		}
	}

	domain d18.local {
		root /var/www;
		index index.html;

		location / {
			allow_methods GET POST DELETE;
			autoindex off;
		}
	}

	domain d19.local {
		root /var/www;
		index index.html;

		location / {
			allow_methods GET POST DELETE;
			autoindex off;
		}
	}

	domain d20.local {
		root /var/www;
		index index.html;

		location / {
			allow_methods GET POST DELETE;
			autoindex off;
		}
	}

	domain d21.local {
		root /var/www;
		index index.html;

		location / {
			allow_methods GET POST DELETE;
			autoindex off;
		}
	}

	domain d22.local {
		root /var/www;
		index index.html;

		location / {
			allow_methods GET POST DELETE;
			autoindex off;
		}
	}

	domain d23.local {
		root /var/www;
		index index.html;

		location / {
			allow_methods GET POST DELETE;
			autoindex off;
		}
	}

	domain d24.local {
		root /var/www;
		index index.html;

		location / {
			allow_methods GET POST DELETE;
			autoindex off;
		}
	}
}
