socket {
	listen 8100;
	host 127.0.0.1;
	domain s00.local {
		root /var/www;
		index index.html;
		location / {
			allow_methods GET;
			autoindex off;
		}
	}
}

socket {
	listen 8101;
	host 127.0.0.1;
	domain s01.local {
		root /var/www;
		index index.html;
		location / {
			allow_methods GET;
			autoindex off;
		}
	}
}

socket {
	listen 8102;
	host 127.0.0.1;
	domain s02.local {
		root /var/www;
		index index.html;
		location / {
			allow_methods GET;
			autoindex off;
		}
	}
}

socket {
	listen 8103;
	host 127.0.0.1;
	domain s03.local {
		root /var/www;
		index index.html;
		location / {
			allow_methods GET;
			autoindex off;
		}
	}
}

socket {
	listen 8104;
	host 127.0.0.1;
	domain s04.local {
		root /var/www;
		index index.html;
		location / {
			allow_methods GET;
			autoindex off;
		}
	}
}

socket {
	listen 8105;
	host 127.0.0.1;
	domain s05.local {
		root /var/www;
		index index.html;
		location / {
			allow_methods GET;
			autoindex off;
		}
	}
}

socket {
	listen 8106;
	host 127.0.0.1;
	domain s06.local {
		root /var/www;
		index index.html;
		location / {
			allow_methods GET;
			autoindex off;
		}
	}
}

socket {
	listen 8107;
	host 127.0.0.1;
	domain s07.local {
		root /var/www;
		index index.html;
		location / {
			allow_methods GET;
			autoindex off;
		}
	}
}

socket {
	listen 8108;
	host 127.0.0.1;
	domain s08.local {
		root /var/www;
		index index.html;
		location / {
			allow_methods GET;
			autoindex off;
		}
	}
}

socket {
	listen 8109;
	host 127.0.0.1;
	domain s09.local {
		root /var/www;
		index index.html;
		location / {
			allow_methods GET;
			autoindex off;
		}
	}
}
