socket {
	# listen 1;
	# port 1 requires sudo
	listen 1024;
	host 127.0.0.1;

	domain low-port.local {
		root /var/www;
		index index.html;

		location / {
			allow_methods GET;
			autoindex off;
		}
	}
}

socket {
	listen 65535;
	host 127.0.0.1;

	domain high-port.local {
		root /var/www;
		index index.html;

		location / {
			allow_methods GET POST DELETE;
			autoindex off;
		}
	}
}
