server {
    listen 8086;
    server_name redirect.local;
    host 127.0.0.1;
    root docs/fusion_web/;
    index index.html;

    location / {
        allow_methods GET;
        autoindex off;
    }

    location /old-docs {
        return /docs;
    }

    location /docs {
        allow_methods GET;
        autoindex on;
        index index.html;
    }
}
