server {
    listen 1;
    server_name low-port.local;
    host 127.0.0.1;
    root docs/fusion_web/;
    index index.html;

    location / {
        allow_methods GET;
        autoindex off;
    }
}

server {
    listen 65535;
    server_name high-port.local;
    host 127.0.0.1;
    root docs/fusion_web/;
    index index.html;

    location / {
        allow_methods GET POST DELETE;
        autoindex off;
    }
}
