socket {
	listen 8080;
	host 127.0.0.1;

	domain unknown-method.local {
		root /var/www;
		index index.html;

		location / {
			root /var/www/html;
			allow_methods GET SCRATCH;
			autoindex off;
		}
	}
}
