socket {
	listen 8282;
	host 127.0.0.1;

	domain self-redirect.local {
		root /var/www;
		index index.html;

		location / {
			allow_methods GET;
			autoindex off;
		}

		location /start {
			redirect /one/;
		}

		location /one {
			redirect /two/;
		}

		location /two {
			redirect /three/;
		}

		location /three {
			redirect /four/;
		}

		location /four {
			redirect /five/;
		}

		location /five {
			redirect /six/;
		}

		location /six {
			allow_methods GET HEAD;
		}
	}
}
