server {
    listen 8083;
    server_name localhost;
    host 127.0.0.1;
    root docs/fusion_web/;
    index index.html;

    location / {
        allow_methods GET POST DELETE;
        autoindex off;
    }
