server {
    listen 8084;
    server_name uploads.local;
    host 127.0.0.1;
    root docs/fusion_web/;
    client_max_body_size 3000000;
    index index.html;
    error_page 404 error_pages/404.html;

    location / {
        allow_methods GET;
        autoindex off;
    }

    location /uploads {
        root docs/fusion_web/;
        allow_methods GET POST DELETE;
        autoindex on;
        index index.html;
    }
}
