socket {
	listen 8082;
	host 127.0.0.1;

	domain localhost 127.0.0.1 {
		root /home/ben/Public/Testing;
		index index.html;
		client_max_body_size 104857600;

		location / {
			allow_methods GET;
		}

		location /cgi-bin {
			allow_methods GET POST HEAD;
			interpreter .py /run/current-system/sw/bin/python3;
			interpreter .sh /home/ben/Public/Testing/cgi_tester;
			interpreter .bla /home/ben/Public/Testing/cgi_tester;
		}

		location /post_body {
			allow_methods POST;
			client_max_body_size 100;
		}

		location /directory {
			alias /home/ben/Public/Testing/YoupiBanane;
			index youpi.bad_extension;
			allow_methods GET POST;
			interpreter .bla /home/ben/Public/Testing/cgi_tester;
		}
	}
}
