location /orphan {
    allow_methods GET;
    autoindex on;
}

server {
    listen 8082;
    server_name localhost;
    host 127.0.0.1;
    root docs/fusion_web/;
    index index.html;

    location / {
        allow_methods GET;
        autoindex off;
    }
}
