server {
    listen 8099;
    server_name aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.local;
    host 127.0.0.1;
    root docs/fusion_web/really/long/path/segment/for/parser/stress/testing/configuration/files/and/static/content/;
    client_max_body_size 2147483647;
    index index.html;

    location /cgi-bin {
        root ./;
        allow_methods GET POST DELETE;
        index stress.py;
        cgi_path /usr/bin/python3 /bin/bash /usr/bin/perl /usr/bin/ruby;
        cgi_ext .py .sh .pl .rb .cgi .fcgi .php .lua .js .ts;
    }

    location / {
        allow_methods GET POST DELETE;
        autoindex off;
    }
}
