server {
    listen 8100;
    server_name s00.local;
    host 127.0.0.1;
    root docs/fusion_web/;
    index index.html;
    location / { allow_methods GET; autoindex off; }
}

server {
    listen 8101;
    server_name s01.local;
    host 127.0.0.1;
    root docs/fusion_web/;
    index index.html;
    location / { allow_methods GET; autoindex off; }
}

server {
    listen 8102;
    server_name s02.local;
    host 127.0.0.1;
    root docs/fusion_web/;
    index index.html;
    location / { allow_methods GET; autoindex off; }
}

server {
    listen 8103;
    server_name s03.local;
    host 127.0.0.1;
    root docs/fusion_web/;
    index index.html;
    location / { allow_methods GET; autoindex off; }
}

server {
    listen 8104;
    server_name s04.local;
    host 127.0.0.1;
    root docs/fusion_web/;
    index index.html;
    location / { allow_methods GET; autoindex off; }
}

server {
    listen 8105;
    server_name s05.local;
    host 127.0.0.1;
    root docs/fusion_web/;
    index index.html;
    location / { allow_methods GET; autoindex off; }
}

server {
    listen 8106;
    server_name s06.local;
    host 127.0.0.1;
    root docs/fusion_web/;
    index index.html;
    location / { allow_methods GET; autoindex off; }
}

server {
    listen 8107;
    server_name s07.local;
    host 127.0.0.1;
    root docs/fusion_web/;
    index index.html;
    location / { allow_methods GET; autoindex off; }
}

server {
    listen 8108;
    server_name s08.local;
    host 127.0.0.1;
    root docs/fusion_web/;
    index index.html;
    location / { allow_methods GET; autoindex off; }
}

server {
    listen 8109;
    server_name s09.local;
    host 127.0.0.1;
    root docs/fusion_web/;
    index index.html;
    location / { allow_methods GET; autoindex off; }
}
