server {
    listen 70000;
    server_name localhost;
    host 999.999.999.999;
    root docs/fusion_web/;
    index index.html;

    location / {
        allow_methods GET;
        autoindex off;
    }
}
