server {
    listen 8115;
    server_name many-locations.local;
    host 127.0.0.1;
    root docs/fusion_web/;
    index index.html;

    location / {
        allow_methods GET;
        autoindex off;
    }

    location /l00 { 
		allow_methods GET POST; 
		autoindex off; 
		}
    location /l01 { allow_methods GET POST; autoindex on; }
    location /l02 { allow_methods GET POST; autoindex off; }
    location /l03 { allow_methods GET POST; autoindex on; }
    location /l04 { allow_methods GET POST; autoindex off; }
    location /l05 { allow_methods GET POST; autoindex on; }
    location /l06 { allow_methods GET POST; autoindex off; }
    location /l07 { allow_methods GET POST; autoindex on; }
    location /l08 { allow_methods GET POST; autoindex off; }
    location /l09 { allow_methods GET POST; autoindex on; }
    location /l10 { allow_methods GET POST; autoindex off; }
    location /l11 { allow_methods GET POST; autoindex on; }
    location /l12 { allow_methods GET POST; autoindex off; }
    location /l13 { allow_methods GET POST; autoindex on; }
    location /l14 { allow_methods GET POST; autoindex off; }
    location /l15 { allow_methods GET POST; autoindex on; }
    location /l16 { allow_methods GET POST; autoindex off; }
    location /l17 { allow_methods GET POST; autoindex on; }
    location /l18 { allow_methods GET POST; autoindex off; }
    location /l19 { allow_methods GET POST; autoindex on; }
    location /l20 { allow_methods GET POST; autoindex off; }
    location /l21 { allow_methods GET POST; autoindex on; }
    location /l22 { allow_methods GET POST; autoindex off; }
    location /l23 { allow_methods GET POST; autoindex on; }
    location /l24 { allow_methods GET POST; autoindex off; }
}
