server {
	listen 8080;
	host 127.0.0.1;
	server_name example.com;
	root /mnt/c/Users/Sebwo/OneDrive/Desktop/42-Coding/111111/WebServer/MVP/MyServer/html;
	index index.html;
	error_page 400 /mnt/c/Users/Sebwo/OneDrive/Desktop/42-Coding/111111/WebServer/MVP/MyServer/errors/400.html;
	error_page 403 /mnt/c/Users/Sebwo/OneDrive/Desktop/42-Coding/111111/WebServer/MVP/MyServer/errors/403.html;
	error_page 404 /mnt/c/Users/Sebwo/OneDrive/Desktop/42-Coding/111111/WebServer/MVP/MyServer/errors/404.html;
	error_page 405 /mnt/c/Users/Sebwo/OneDrive/Desktop/42-Coding/111111/WebServer/MVP/MyServer/errors/405.html;
	error_page 500 /mnt/c/Users/Sebwo/OneDrive/Desktop/42-Coding/111111/WebServer/MVP/MyServer/errors/500.html;
	error_page 505 /mnt/c/Users/Sebwo/OneDrive/Desktop/42-Coding/111111/WebServer/MVP/MyServer/errors/505.html;

	location / {
		# Serves /home/ben/Public/html/index.html, /home/ben/Public/html/about.html, etc.
		# index index.html;
		allow_methods GET;
	}

	location /css {
		# Maps to /home/ben/Public/html/css
		allow_methods GET;
		autoindex off;
	}

	location /blog {
		# Maps to /home/ben/Public/html/blog
		allow_methods GET DELETE;
		autoindex on;
	}

	location /products {
		# Maps to /home/ben/Public/html/products
		allow_methods GET;
		autoindex off;
	}

	location /wardrobe {
		# Maps to /home/ben/Public/html/narnia
		redirect /narnia;
	}


	location /narnia {
		# index index.html;
		allow_methods GET;
	}

	location /uploads {
		root /mnt/c/Users/Sebwo/OneDrive/Desktop/42-Coding/111111/WebServer/MVP/MyServer;
		# Maps to /home/ben/Public/uploads/
		allow_methods GET POST;
	}

	location /cgi-bin {
		root /mnt/c/Users/Sebwo/OneDrive/Desktop/42-Coding/111111/WebServer/MVP/MyServer;
		# Maps to /home/ben/Public/cgi-bin/
		interpreter .py /usr/bin/python3;
		interpreter .sh /bin/bash;
	}

	location /api {
		root /mnt/c/Users/Sebwo/OneDrive/Desktop/42-Coding/111111/WebServer/MVP/MyServer;
		# Maps to /home/ben/Public/api/
		allow_methods GET POST DELETE;
	}
}
