socket {
    listen 8086;
    host 127.0.0.1;

    domain redirect.local {
        root /var/www;
        index index.html;

        location / {
            allow_methods GET;
            autoindex off;
        }

        location /old-docs {
            redirect /docs/;
        }

        location /docs {
            allow_methods GET;
            autoindex on;
            index index.html;
        }
    }
}
