socket {
    listen 8084;
    host 127.0.0.1;

    domain uploads.local {
        root /var/www;
        client_max_body_size 3000000;
        index index.html;

        location / {
            allow_methods GET;
            autoindex off;
        }

        location /uploads {
            root /var/www;
            allow_methods GET POST DELETE;
            autoindex on;
            index index.html;
        }
    }
}
