socket {
    listen 8089;
    host 127.0.0.1;

    domain good-cgi.local {
        root /var/www;

        location /cgi-bin {
            allow_methods GET;
            interpreter .py /usr/bin/python3;
        }
    }
}
