server {
    listen 8081;
    server_name localhost;
    host 127.0.0.1;
    root docs/fusion_web/;
    index index.html;
    banana_mode on;

    location / {
        allow_methods GET;
        autoindex off;
    }
}
